version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: gas-station
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  postgres_test:
    image: postgres
    environment:
      POSTGRES_DB: gas-station-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - db-test:/var/lib/postgresql/data

#  app:
#    build:
#      context: .
#    environment:
#      DB_SCHEMA: postgres
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#      DB_HOST: postgres
#    depends_on:
#      - postgres
#    ports:
#      - '3000:3000'

volumes:
  db:
  db-test: